
/*********************************************************************************************
Author:       Harikrishnan G Nair on 9/28/16.
 
 Description: command line shell program in C that interacts with the user in the following way. 
              By default, the shell gives a prompt to the user. When the user types in a command 
              (in response to its prompt) and hits Enter, the shell creates a child process that 
              executes the command he entered and displays the results if any. It then prompts 
              for more user input by displaying the prompt again.
 
              For example, when the user types command ls, the shell should display a listing of 
              files in the current working directory. Your program should achieve this by simply 
              passing this command to the underlying shell and receiving the results generated by 
              it. Do not try to implement the functionality of the command within your own program.
 
              The shell is limited to handling basic commands that do not involve piping and 
              redirection.
 
Copyright © 2016 New York University. All rights reserved.

*******************************************************************************************************/
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
  char command[25];
  while(1)	// Background infinite loop to keep executing the shell until an exit command is received
  {
    printf("usr@linux:~$");       //Print the prompt
    gets(command);	              //Get the input for the shell
    if(strcmp(command,"exit")==0||strcmp(command,"Exit")==0||strcmp(command,"EXIT")==0) // Checking exit conditions
        {
            return 0;
        }
        system(command); // System call to execute the command
  }

return 0;
}



/*
 int execute_fun(char *);
 int main() // start of the simple shell command prompt
 
 {
    int pid=fork();
    char command[25];
    if(pid==0)
    {
        while(1)
        {
            printf("usr@linux:~$");
            gets(command);
            if(strcmp(command,"exit")==0||strcmp(command,"Exit")==0||strcmp(command,"EXIT")==0)
            {
                return 0;
            }
            int d=execute_fun(command);
            if(d==-1)
            {
            printf("command not found");
            }
        }
    }
 return 0;
 }
 
 
 int execute_fun(char* cmd)
 {
 char path[50]="/bin/";
 int d= execl(strcat(path,cmd),cmd,NULL,NULL);
 return d;
 }
 */
